version: "3.8"
services:
  prod:
    container_name: projectManagementBackend
    image:  bxdman/ceprojectmanagement
    environment:
      - DATABASE_URL
      - GOOGLE_CLIENT_ID
      - GOOGLE_SECRET
      - MINIO_ENDPOINT
      - MINIO_CONSOLE
      - MINIO_PORT
      - MINIO_ACCESSKEY
      - MINIO_SECRETKEY
      - MINIO_SSL
      - MINIO_BASEBUCKET
    restart: always
    ports:
      - 3001:5000