name: production-deploy
on:
  push:
    branches: [main]
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
  MINIO_ENDPOINT: ${{ secrets.MINIO_ENDPOINT }}
  MINIO_CONSOLE: ${{ secrets.MINIO_CONSOLE }}
  MINIO_PORT: ${{ secrets.MINIO_PORT }}
  MINIO_ACCESSKEY: ${{ secrets.MINIO_ACCESSKEY }}
  MINIO_SECRETKEY: ${{ secrets.MINIO_SECRETKEY }}
  MINIO_SSL: ${{ secrets.MINIO_SSL }}
  MINIO_BASEBUCKET: ${{ secrets.MINIO_BASEBUCKET }}

jobs:
  lintTest:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Clone Repo ⬇️
        uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: Running Lint
        run: |
          npm run lint ||
          (
              echo '🔨❌ Yoo, you have a problem in your code. Check linter 🔨❌
                  Run yarn lint, add changes and try commit again.';
              false;
          )
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: bxdman/ceprojectmanagement:latest

  deploy:
    runs-on: self-hosted
    needs: [lintTest]
    steps:
      - name: Copy repository
        uses: actions/checkout@v3

      - name: Build the docker-compose stack
        run: docker compose up -d --build

      - name: Clear all docker unused cache
        run: docker system prune -af
